import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Hero from '../components/Hero'


export default function Home() {
  return (
    <div className='bg-slate-700'>
      <Head>
        <title>Fresh Tech Talents</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      

    </div>
  )
}
